version: "3"

volumes:
  mysql:
   driver: local

networks:
  db:
    driver: bridge
  app-network:
    driver: bridge

services:
     # Service Nginx - Serveur Web
  web:
    restart: always
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

     # Service MySQL
  mysql:
    container_name: mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_DATABASE: bedflix
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - db

     # Service PHP-FPM
  php:
     restart: always
     container_name: php
     build:
       context: .
       dockerfile: php.dockerfile
     volumes:
        - ./www:/var/www/html
     networks:
        - app-network

     # phpMyAdmin
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: always
    expose:
      - "40001"
    ports:
      - "40001:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - db

